### ISSUE TITLE
The first generation virtual machine cannot be created

### ISSUE THREAD

**Issue by e9f0accf08912a27** [containers/libhvee#115]
settings.VirtualSystemSubType = "Microsoft:Hyper-V:SubType:1" 
The first generation cannot create a virtual machine, but the second generation works fine. How to solve the problem?

**Comment by gbraad** [comment]
We do not use V1 machines as we went with EFI support for all platforms. I've tried to make it work, but got weird issues from the API about either missing or invalid values. The question would be, why do you need V1?

**Comment by e9f0accf08912a27** [comment]
> We do not use V1 machines as we went with EFI support for all platforms. I've tried to make it work, but got weird issues from the API about either missing or invalid values. The question would be, why do you need V1?

Thanks to gbraad for the reply. Since the original architecture is v1, I hope the community can add the first generation. Thank you.

**Comment by n1hility** [comment]
Since all modern use cases either require or are supported with v2, legacy v1 suppose isn’t currently planned. Since it’s a fairly involved effort, it would take a motivated contributor willing to invest the time energy to make it happen.
