### ISSUE TITLE
Version 0.1.0 mistagged as `v0.1`

### ISSUE THREAD

**Issue by bgilbert** [containers/libhvee#35]
libhvee 0.1.0 is tagged as `v0.1`, but `go get` appears to ignore tags in non-canonical semver form.  I've tested this on a GitHub fork: with only `v0.0.5` and `v0.1` tags, `go get github.com/containers/libhvee` fetches 0.0.5, but with a `v0.1.0` tag, `go get` fetches the newest version.

**Comment by bgilbert** [comment]
(Though, looking at the Git history, this doesn't actually matter for applications using the library.)

**Comment by bgilbert** [comment]
@baude Version 0.2.0 now has the same problem.  Could you retag these releases with proper semver tags?

**Comment by baude** [comment]
@bgilbert better?

**Comment by bgilbert** [comment]
Still not working, I assume because it was tagged as `0.2.0` instead of `v0.2.0`.

**Comment by baude** [comment]
ok, better?

**Comment by bgilbert** [comment]
Yes, it works now, thanks.
