### ISSUE TITLE
Precompiled `kvpctl` missing from latest GitHub releases

### ISSUE THREAD

**Issue by bgilbert** [containers/libhvee#41]
The FCOS Hyper-V docs in https://github.com/coreos/fedora-coreos-docs/pull/545 expect that `kvpctl.exe` will be available from libhvee's GitHub releases, but the last two releases don't have it.  To reduce user confusion, could those be added?

cc @baude

**Comment by fsdrw08** [comment]
New version of kvpctl still missing
