### ISSUE TITLE
Implement missing 'ForceOff' (Kill) option for stopping VM

### ISSUE THREAD

**Issue by gbraad** [containers/libhvee#48]
https://github.com/containers/libhvee/blob/3777cdaa7db846a1356467cf433bc841d2db8d91/pkg/hypervctl/vm.go#L231

**Comment by baude** [comment]
@gbraad see https://github.com/containers/libhvee/pull/50

**Comment by gbraad** [comment]
Can be closed with a dup notice.

Was an observation of missing functionality as a force is often required in the case of OCP: cluster stopped but VM is just taking its time.

**Comment by gbraad** [comment]
Duplicate of #50
