### ISSUE TITLE
Add identifiers/type for Generation 1 and 2

### ISSUE THREAD

**Issue by gbraad** [containers/libhvee#49]
https://github.com/containers/libhvee/blob/3777cdaa7db846a1356467cf433bc841d2db8d91/pkg/hypervctl/system_settings.go#L85C3-L85C23

```golang
// GenerationType defines the VM generation type
type GenerationType string

var (
	Generation1 GenerationType = "Microsoft:Hyper-V:SubType:1"
	Generation2 GenerationType = "Microsoft:Hyper-V:SubType:2"
)
```

**Comment by baude** [comment]
@n1hility this is more up your alley ... got time to handle?

**Comment by gbraad** [comment]
I will be doing this.

Just need to get the Gen1 VM running first, as at the moment I have an issue with a parameter value... Unclear which due to WMI being harder to debug.

**Comment by gbraad** [comment]
The reason to use Gen1 is actually not necessary for our OpenShift images, as they are already set up for GPT. It seems only our Microshift images were classic/legacy MBR-based and we are looking into resolving this:

 - https://github.com/crc-org/snc/issues/801

**Comment by gbraad** [comment]
Not relevant anymore; we only need Gen2
