### ISSUE TITLE
kvpctl.exe can't detect target Hyper-V VMs in Intel E3 / E5 CPU machines

### ISSUE THREAD

**Issue by yangboroy** [containers/libhvee#56]
Summary:
Based on `Provisioning Fedora CoreOS on Microsoft Hyper-V`, find that kvpctl.exe couldn't detect target Hyper-V VMs in Intel E3 / E5 CPU machines.

Steps to Reproduce:
1. Prepare a Windows Server 2022 or Windows 10 in a Intel(R) Xeon(R) CPU E5 / E3 machine.
2. Install a fedora-coreos VM in Hyper-V, and confirm Get-VM can detect it.
3. Follow the steps (prepare all required files and tools) to execute .\kvpctl.exe <name_of_vm> add-ign <path_to_ign_file>.
```
.\kvpctl.exe fedora-coreos-38.20230902.3.0 add-ign .\example.ign
Find machine failed: could not find virtual machine "fedora-coreos-38.20230902.3.0"
```
4. Prepare a Windows Server 2022 or Windows 10 in a AMD EPYC machine.
5. Install a fedora-coreos VM in Hyper-V, and confirm Get-VM can detect it.
6. Follow the steps (prepare all required files and tools) to execute .\kvpctl.exe <name_of_vm> add-ign <path_to_ign_file>.
```
.\kvpctl.exe fedora-coreos-38.20230902.3.0 add-ign .\example.ign
added key:  ignition.config.0
```

So, seems kvpctl can't detect Hyper-V VMs in Intel E series.

**Comment by herrart** [comment]
Hi. What version do you used? I had the same problem on 0.4.0. Try to download current master and build kvpctl from source. This helped me.

**Comment by yangboroy** [comment]
Have rebuilt kvpctl from current master. It works.

Thanks. a loooooot @herrart
